### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by swrobel** [rtcreativegroup/active_campaign_rb#16]
This seems to be the only gem I've found that's built around the RESTful v3 API, but it doesn't seem to have been released to rubygems. Any plans for doing so?

**Comment by clintmiller** [comment]
@swrobel Thanks for asking. I would have to review this and see if it's in a releasable state. It uses the v3 API in some places and the v2 in others. Additionally, it was pretty specific to the way we wanted to use the ActiveCampaign in our web app. All that to say, getting this released to rubygems.org is not really a priority.

However, I'd be happy for you to fork it and make use of it for your project(s).
